before_script:
  - if [ ! $TEST_PARAMETER ]; then export TEST_PARAMETER=''; fi

stages:
  - quality gate

quality:
  stage: quality gate
  image:
    name: mcr.microsoft.com/dotnet/core/sdk:3.0.101-bionic
    entrypoint: [""]
  script:
    - export PATH=${PATH}:/root/.dotnet/tools
    - dotnet sonarscanner begin /k:"vdlk-${CI_PROJECT_ID}" /n:"${CI_PROJECT_PATH_SLUG}" /d:sonar.host.url="${SONAR_HOST_URL}" /d:sonar.language="cs" /d:sonar.exclusions="**/bin/**/*,**/obj/**/*" /d:sonar.login="${SONAR_LOGIN}"  /d:sonar.cs.opencover.reportsPaths="${PROJECT_TEST_PATH}/coverage.opencover.xml" /d:sonar.coverage.exclusions="**Test*.cs,Program.cs"
    - dotnet restore --configfile ${PROJECT_API_PATH}/nuget.config ${PROJECT_API_PATH}
    - dotnet restore --configfile ${PROJECT_TEST_PATH}/nuget.config ${PROJECT_TEST_PATH}
    - dotnet build ${PROJECT_SLN_PATH}
    - dotnet test ${PROJECT_TEST_PATH} ${TEST_PARAMETER} /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - dotnet sonarscanner end /d:sonar.login=${SONAR_LOGIN}
  only:
    refs:
      - branches
  except:
    refs:
      - master
      - SWAGGERHUB
  artifacts:
    expire_in: 1 hour
